# Generated by Django 5.0 on 2025-10-18 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographicRegion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lattitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoviePopularity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('popularity', models.IntegerField()),
                ('geographic_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.geographicregion')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
    ]
