# Generated by Django 5.0 on 2025-10-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_geographicregion_moviepopularity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moviepopularity',
            unique_together={('movie', 'geographic_region')},
        ),
        migrations.AddField(
            model_name='moviepopularity',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='moviepopularity',
            name='purchase_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moviepopularity',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='moviepopularity',
            name='popularity',
        ),
    ]
